# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e251a4923ff39a323e4f79b346396cf8a1a32e7fa98d1d8f9e634afe24639630fe40c26c909b6d0d9dbe8c7a5f1be11f46258070b0e6d16a115a93d09557d882

test:
  secret_key_base: 8073f3ef518a4ddf6f57810217d177cc70c36b41d17bf2751603709876efe9e04b77e00184eb38f4324460efe07fb07f115dbf0e869d0e66600c1995e19c4296

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
